name: Upload content to S3
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-aws
      - run: |
          echo HelloWorld12345 > index.html
          aws s3 cp index.html s3://${{ env.WEB_BUCKET_NAME }}/ --cache-control 'no-cache'
        shell: bash
