name: Visual Regression Test
on:
  workflow_dispatch:

env:
  REG_NOTIFY_CLIENT_ID: ${{ secrets.REG_NOTIFY_CLIENT_ID }}
  WEB_BUCKET_NAME: ${{ secrets.WEB_BUCKET_NAME }}
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
  CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  id-token: write

jobs:
  vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-node-modules
        id: cache-node-modules
      - uses: ./.github/actions/setup-aws
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run reg-suit
        run: npm run vrt:run
